on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Publish
        run: dotnet publish -c Release

      - uses: actions/checkout@v2
      - name: Upload ftp
        uses: genietim/ftp-action@releases/v4
        with:
          host: elsacoredemo.somee.com
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "./bin/Release/net7.0/publish"
          remoteDir: "/."
