name: Deploy Release to Server

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download release assets
        uses: actions/download-artifact@v3
        with:
          name: release-assets
          path: ./release-assets

      - name: 📂 Upload ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: elsacoredemo.somee.com
          username: hn8888
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: www.elsacoredemo.somee.com/
