name: Tag to Release

on:
  push:
    tags:
      - '*'

jobs:
  publish_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 🚚 Build and Publish
        run: dotnet publish -c Release -o publish

      - name: Get tag name
        id: get_tag
        run: echo "::set-output name=TAG_NAME::$(git tag --points-at ${{ github.sha }})"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.get_tag.outputs.TAG_NAME }}
          release_name: Release ${{ steps.get_tag.outputs.TAG_NAME }}
          body: |
            Release notes for ${{ steps.get_tag.outputs.TAG_NAME }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        id: upload_release_assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/*
          asset_name: MyApp.zip  # Adjust the asset name
          asset_content_type: application/zip
